"""
Dockrion Generated Runtime
==========================
Agent: test-agentMode: Entrypoint (framework agent)
Framework: langgraph
Entrypoint: tests.fixtures.mock_agent:build_agentDescription: Test agent for SDK testing

Auto-generated by Dockrion SDK v1.0.0
Do not edit manually - regenerate using `dockrion build`
"""
import sys
import os
from pathlib import Path

# Add project root to Python path for agent module imports
# Use dockrion_common utility for consistent path resolution
from dockrion_common import setup_module_path

current_dir = Path(__file__).parent
module_path = "tests.fixtures.mock_agent:build_agent"
# Setup Python path to find the agent module
project_root = setup_module_path(module_path, current_dir.parent)

from dockrion_runtime import create_app
from dockrion_schema import DockSpec

# Try to load .env from project root (if python-dotenv is available)
try:
    from dotenv import load_dotenv
    env_file = project_root / '.env'
    load_dotenv(env_file)
except ImportError:
    pass  # python-dotenv not installed, skip .env loading

# ============================================================================
# Agent Specification (Embedded from Dockfile.yaml)
# ============================================================================

SPEC_DATA = {'version': '1.0', 'agent': {'name': 'test-agent', 'description': 'Test agent for SDK testing', 'entrypoint': 'tests.fixtures.mock_agent:build_agent', 'handler': None, 'framework': 'langgraph'}, 'io_schema': {'input': {'type': 'object', 'properties': {'text': {'type': 'string'}}, 'required': [], 'items': None, 'description': None}, 'output': {'type': 'object', 'properties': {'result': {'type': 'string'}}, 'required': [], 'items': None, 'description': None}}, 'arguments': {}, 'policies': None, 'auth': None, 'observability': None, 'expose': {'rest': True, 'streaming': 'sse', 'port': 8080, 'host': '0.0.0.0', 'cors': None}, 'metadata': None, 'secrets': None}

# ============================================================================
# Create Application
# ============================================================================

# Parse and validate the embedded specification
spec = DockSpec.model_validate(SPEC_DATA)

# Create the FastAPI application using the runtime factory# Entrypoint mode: framework agent
app = create_app(
    spec=spec,
    agent_entrypoint="tests.fixtures.mock_agent:build_agent"
)
# ============================================================================
# Main Entry Point
# ============================================================================

if __name__ == "__main__":
    import uvicorn
    
    host = "0.0.0.0"
    port = 8080
    
    print(f"🚀 Starting test-agent on {host}:{port}")
    uvicorn.run(
        app,
        host=host,
        port=port,
        log_level="info"
    )

